Adapt iso20022ReportReference
swissfintechinnovations/ca-payment pull request #72
Opened 2023-12-27 15:40 UTC by svenbiellmann

New iso20022ReportReference properties (schemaVersion, dateFrom, dateTo) are added. The added properties are optional.

2024-01-10 10:29 UTC, simonmeyerm requested changes
Please remove element "[conditionList](https://github.com/swissfintechinnovations/ca-payment/pull/72/files#diff-5cf1fd70d56ab8596d6b63f9a0b0bb9dfbe5a5cfbd04a0c03feaa35b2e924d73R310)" from properties in endpoint response. 
This element does not exist in bLink specification and has no additional value from my perspective. 
The element was added with the initial merge with the ISO20022 endpoints.

2024-01-10 15:39 UTC, svenbiellmann commented
> Please remove element "[conditionList](https://github.com/swissfintechinnovations/ca-payment/pull/72/files#diff-5cf1fd70d56ab8596d6b63f9a0b0bb9dfbe5a5cfbd04a0c03feaa35b2e924d73R310)" from properties in endpoint response. This element does not exist in bLink specification and has no additional value from my perspective. The element was added with the initial merge with the ISO20022 endpoints.

Element "conditonList" removed from properties in endpoint response and pull request updated.

2024-01-22 08:55 UTC, simonmeyerm approved these changes

2024-01-22 09:46 UTC, dkoeni approved these changes
Changes approved.

2024-01-22 09:50 UTC, merged